### ISSUE TITLE
Empty HPO does not generate OMIM phenotype file

### ISSUE THREAD

**Issue by arine** [LiuzLab/AI_MARRVEL#2]
When hpo.txt is an empty file, the pipeline fails because phenoSim.R does not generate OMIM HPO file {{Job ID}}-dx, so main.py fails.
Log:
```
Feature engineering                                                                                                               
input file: /out/jobid-vep-1.txt                                                                               
type of input file: vepAnnotTab                                                                                                   
outPrefix: /out/rami-test/r1                                                                                                      
modules: curate,conserve                                                                                                          
modules list: ['curate', 'conserve']                                                                                              
Traceback (most recent call last):                                                                                                
  File "/run/annotation/main.py", line 486, in <module>                                                                           
    main()                                                                                                                        
  File "/run/annotation/main.py", line 174, in main                                                                               
    omimHPOScoreDf = pd.read_csv(fileName, sep='\t')                                                                              
  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 311, in wrapper                                  
    return func(*args, **kwargs)                                                                                                  
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 680, in read_csv                               
    return _read(filepath_or_buffer, kwds)                                                                                        
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 575, in _read                                  
    parser = TextFileReader(filepath_or_buffer, **kwds)          
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 934, in __init__                               
    self._engine = self._make_engine(f, self.engine)                                                                              
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine                          
    self.handles = get_handle(  # type: ignore[call-overload]                                                                     
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 786, in get_handle
    handle = open(                                                                                                                
FileNotFoundError: [Errno 2] No such file or directory: '/out/jobid-dx'  
```

**Comment by arine** [comment]
Resolved at commit 5d7e32ae160d10447e640e7cda303df4e6f36ae2
